- name: play level variables
  hosts: local
  connection: local 
  tasks:
  - name: print course info 
    ansible.builtin.debug:
      msg: "Hello Ansible, Course Duration: 10HR, Trainer: pal"


- name: play level variables2
  hosts: local
  connection: local 
  tasks:
  - name: print course info 
    ansible.builtin.debug:
      msg: "Hello Ansible, Course Duration: 10HR, Trainer: pal"