- name: prompt
  hosts: local
  connection: local
  vars_prompt: 
  - name: username
    prompt: please enter your username 
    private: true 
  
  - name: password 
    prompt: enter your password 
    private: true 
  tasks:
  - name: login details
    ansible.builtin.debug:
      msg: "Hello {{ username }}, password: {{ password }}"