- name: functions
  hosts: local 
  connection: local 
  vars:
    persons: "ramesh,suresh,rakesh"
  tasks: 
  - name: print name 
    ansible.builtin.debug:
      msg: "hello, {{ persons | default('ramesh') }}"


  - name: print names 
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"
