- name: functions
  hosts: local 
  connection: local 
  vars:
    persons: "ramesh,suresh,rakesh"
  tasks: 
  - name: print name 
    ansible.builtin.debug:
      msg: "hello,{{ persons | default('ramesh') }}"


  - name: print names 
    ansible.builtin.debug:
      msg: "Hello,{{ persons | split(',') }}"


  - name: maps to list
    vars:
      course:
        duration: 10 
        trainer: pal 
        name: devops
    ansible.builtin.debug:
      msg: "course:{{ course | dict2items }}"

  - name : list to maps
    vars:
      course:
      - {'key': some, 'value': 'devops'}
      - {'key': 'duration', 'value': '10'}
      - {'key': 'trainer', 'value': 'pal'}
    ansible.builtin.debug:
      msg: "course info {{ course | items2dict }}"

  - name : to upper case 
    vars:
      name: "paldinakar alle"
    ansible.builtin.debug:
      msg: "my name is:{{ name | upper }}"


  - name: to lower case 
    vars:
      name: "PALDINAKAR"
    ansible.builtin.debug:
      msg: "my name is: {{ name | lower }}"
  