- name: user creation 
  hosts: local 
  connection: local 
  tasks: 
  - name: creation of user
    ansible.builtin.command: id roboshop 
    register: output
    ignore_errors: true 

  - name: create user 
    become: yes
    ansible.builtin.command: useradd roboshop 
    when: output.rc  != 0  

  - name: dont create 
    ansible.builtin.debug: 
      msg: "user already exists"
    when: output.rc == 0